VelvetLeaves/VelvetLeaves.App/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.Category;
using static VelvetLeaves.Common.ApplicationConstants;
using static VelvetLeaves.Web.Infrastructure.Extensions.ControllerExtensions;

namespace VelvetLeaves.App.Areas.Admin.Controllers
{
    [Area(AdminAreaName)]
    [Authorize(Roles = AdminAndModeratorRoleNames)]
    public class CategoriesController : Controller
    {
        private readonly IImageService _imageService;
        private readonly ICategoryService _categoryService;
        private readonly ILogger<CategoriesController> _logger;
        public CategoriesController(
            IImageService imageService,
            ICategoryService categoryService,
            ILogger<CategoriesController> logger)
        {
            _imageService = imageService;
            _categoryService = categoryService;
            _logger = logger;
        }

        [HttpGet]
        [DisplayName("Add")]
        
        public IActionResult Add()
        {
            
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CategoryFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                string? imageId = await _imageService.CreateAsync(model.Image);

                if (imageId == null)
                {
                    ModelState.AddModelError("Image", "Image upload unsuccessful.");
                }


                await _categoryService.AddCategoryAsync(model.Name, imageId!);


                return RedirectToAction("All", "Products");
            }
            catch (Exception e)
            {
                _logger.LogError(e,"Exception thrown in {0} by {1}",this.GetType().Name, System.Reflection.MethodBase.GetCurrentMethod()?.Name ?? null);
                return NotFound();
            }

            

            
        }

		[HttpGet]
        public async Task<IActionResult> Edit(int categoryId)
        {
            try
            {
                var model = await _categoryService.GetForEditAsync(categoryId);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }

            
		}

		[HttpPost]
        public async Task<IActionResult> Edit(CategoryEditFormViewModel model)
		{
			if (!ModelState.IsValid)
			{
                return View(model);
			}

            try
            {
                await _categoryService.EditAsync(model);
                return RedirectToAction("All", "Products");
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
            
        }

		[HttpGet]
        [DisplayName("Delete")]
        public async Task<IActionResult> Delete(int categoryId)
		{
            try
            {
                await _categoryService.DeleteAsync(categoryId);
                return RedirectToAction("All", "Products");
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
            
        }
    }
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Controllers/ProductSeriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.ProductSeries;
using static VelvetLeaves.Common.ApplicationConstants;

namespace VelvetLeaves.App.Areas.Admin.Controllers
{
	[Area(AdminAreaName)]
	[Authorize(Roles = AdminAndModeratorRoleNames)]
	public class ProductSeriesController : Controller
	{
		
		private readonly IProductSeriesService _productSeriesService;
		private readonly ILogger<ProductSeriesController> _logger;

		public ProductSeriesController
			(
            IProductSeriesService productSeriesService, ILogger<ProductSeriesController> logger)
        {
            
            _productSeriesService = productSeriesService;
			_logger = logger;
        }



        [HttpGet]
		public async Task<IActionResult> Add(int categoryId, int subcategoryId)
		{



			var model = new ProductSeriesFormViewModel()
			{
				CategoryId = categoryId,
				SubcategoryId = subcategoryId
			};
            try
            {
				model = await _productSeriesService.PopulateModel(model);
				return View(model);
			}
            catch (Exception e)
            {
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
            }
			
		}

		[HttpPost]
		public async Task<IActionResult> Add(ProductSeriesFormViewModel model)
		{
			try
			{

				if (!ModelState.IsValid)
            {
				model = await _productSeriesService.PopulateModel(model);
				return View(model);
			}

			
				await _productSeriesService.AddAsync(model);
				return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}");
			}
			catch (Exception e)
			{
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
			}

			
		}

        [HttpGet]
		public async Task<IActionResult> FetchProductSeries(int subcategoryId)
        {
			try
			{
				var model = await _productSeriesService.ProductSeriesBySubcategoryIdAsync(subcategoryId);
				return Json(model);
			}
			catch (Exception e)
			{
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
			}

			
        }

		[HttpGet]
		public async Task<IActionResult> Edit(int productSeriesId)
		{
			try
			{
				var model = await _productSeriesService.GetProductSeriesByIdAsync(productSeriesId);
				ViewData["id"] = productSeriesId;
				return View(model);
			}
			catch (Exception e)
			{
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
			}

			
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int productSeriesId, ProductSeriesFormViewModel model)
		{
			try
			{

				if (!ModelState.IsValid)
			{
				model = await _productSeriesService.PopulateModel(model);
				return View(model);
			}


			
				await _productSeriesService.EditAsync(productSeriesId, model);
				return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}");
			}
			catch (Exception e)
			{
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
			}
			
		}

		[HttpGet]
		public async Task<IActionResult> Delete(int productSeriesId, int subcategoryId, int categoryId)
		{
			try
			{
				await _productSeriesService.DeleteAsync(productSeriesId);
				return LocalRedirect($"~/Admin/Products/All?categoryId={categoryId}&subcategoryId={subcategoryId}");
			}
			catch (Exception e)
			{
				_logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
				return NotFound();
			}

			
		}
	}
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VelvetLeaves.Data;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.Product;
using VelvetLeaves.ViewModels.ProductSeries;
using static VelvetLeaves.Common.ApplicationConstants;

namespace VelvetLeaves.Web.App.Areas.Admin.Controllers
{
    [Area(AdminAreaName)]
    [Authorize(Roles = $"{AdminRoleName},{ModeratorRoleName}")]

    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductSeriesService _productSeriesService;
        private readonly IImageService _imageService;
        private readonly ILogger<ProductsController> _logger;
        public ProductsController(
            IProductService productService,
            IProductSeriesService productSeriesService,
            IImageService imageService,
            ILogger<ProductsController> logger
            )
        {
            _productService = productService;
            _productSeriesService = productSeriesService;
            _imageService = imageService;
            _logger = logger;   
        }
        /// <summary>
        /// Returns all products, grouped by product series, then by subcategory, then by category, to be browsed in a tree-like structure.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> All(int? categoryId, int? subcategoryId, int? productSeriesId)
        {
            try
            {
                var model = await _productService.GetProductTreeAsync(categoryId, subcategoryId, productSeriesId);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int productId)
        {
            try
            {
                var model = await _productService.GetFormForEditAsync(productId);
                return View(model);

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductEditFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ImageIds = model.StartingImageIds!.ToList();
                return View(model);
            }

            try
            {
                await _productService.UpdateAsync(model);
                return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}&productSeriesId={model.ProductSeriesId}");

            }
            catch(Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }



            //return RedirectToAction("All", "Products");


        }

        [HttpGet]
        public async Task<IActionResult> Add(int categoryId, int subcategoryId, int productSeriesId)
        {
            try
            {
                var model = await _productService.GetFormForAddAsync(categoryId, subcategoryId, productSeriesId);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductFormViewModel model)
        {
            try
            {

                if (!ModelState.IsValid)
            {
                var newOptions = await _productService.GetFormForAddAsync(model.CategoryId, model.SubcategoryId, model.ProductSeriesId);
                model.CategoryOptions = newOptions.CategoryOptions;
                model.SubcategoryOptions = newOptions.SubcategoryOptions;
                model.ProductSeriesOptions = newOptions.ProductSeriesOptions;
                model.MaterialOptions = newOptions.MaterialOptions;
                model.TagOptions = newOptions.TagOptions;
                model.ColorOptions = newOptions.ColorOptions;

                return View(model);
            }
            
                var imageIds = await _imageService.CreateRangeAsync(model.Images);
                if (imageIds.Any(id => id == null))
                {
                    ModelState.AddModelError("Image", "Image upload unsuccessful.");
                    return View(model);
                }

                model.ImageIds = imageIds!;

                await _productService.AddAsync(model);
                return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}&productSeriesId={model.ProductSeriesId}");

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return BadRequest();
            }

        }

        [HttpGet]
        public async Task<IActionResult> FetchDefaultValues(int productSeriesId)
        {
            try
            {
                var model = await _productSeriesService.GetDefaultValues(productSeriesId);
                return Json(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }

        [HttpGet]
        public async Task<IActionResult> Delete(int productId, int categoryId, int subcategoryId, int productSeriesId)
        {
            try
            {
                await _productService.DeleteAsync(productId);
                return LocalRedirect($"~/Admin/Products/All?categoryId={categoryId}&subcategoryId={subcategoryId}&productSeriesId={productSeriesId}");

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }
    }
}

VelvetLeaves/VelvetLeaves.App/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VelvetLeaves.Service.Models;
using VelvetLeaves.Services;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.Product;

namespace VelvetLeaves.Web.App.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        
        private readonly ILogger<ProductsController> _logger;
        public ProductsController(
            IProductService productService,
            ILogger<ProductsController> logger
            )
        {
            _productService = productService;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> ProductsFiltered(ProductsQueryModel queryModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            try
            {
                queryModel = await _productService.ProductsFilteredAndPagedAsync(queryModel);
                return View("Products", queryModel);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }

        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var model = await _productService.DetailsByIdAsync(id);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
        } 
    }
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Views/Products/Add.cshtml
@model ProductFormViewModel

	@{
	ViewData["Title"] = "Add Product";

}


<div class="container mt-5">
		<h2 class="mb-3">@ViewData["Title"]</h2>

	<form id="categoryForm" enctype="multipart/form-data" method="post">
		<div class="mb-3">
			
			<label asp-for="CategoryId" class="form-label">Category</label>
			<select asp-for="CategoryId" class="form-select category-select" aria-label="Select Category">
				@foreach (var category in Model.CategoryOptions)
				{
					@if (category.Id == Model.CategoryId)
					{
						<option value="@category.Id" selected>@category.Name</option>
					}
					else
					{
						<option value="@category.Id">@category.Name</option>
					}
				}
			</select>

		</div>

		<div class="mb-3">
			<label asp-for="SubcategoryId" class="form-label">Subcategory</label>
			<select asp-for="SubcategoryId" class="form-select subcategory-select" aria-label="Select Subcategory">
				@foreach (var subcategory in Model.SubcategoryOptions)
				{
					@if (subcategory.Id == Model.CategoryId)
					{
						<option value="@subcategory.Id" selected>@subcategory.Name</option>
					}
					else
					{
						<option value="@subcategory.Id">@subcategory.Name</option>
					}
				}
			</select>

		</div>

		<div class="mb-3">
			<label asp-for="ProductSeriesId" class="form-label">Product Series</label>
			<select asp-for="ProductSeriesId" class="form-select productseries-select" aria-label="Select Product Series">
				@foreach (var series in Model.ProductSeriesOptions)
				{
					@if (series.Id == Model.ProductSeriesId)
					{
						<option value="@series.Id" selected>@series.Name</option>
					}
					else
					{
						<option value="@series.Id">@series.Name</option>
					}
				}
			</select>

		</div>

		<div class="mb-3">
			<label asp-for="Name" class="form-label">Product Name</label>
			<input asp-for="Name" value="@Model.Name" class="form-control name-input" autocomplete="Enter series name here" aria-required="true" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>



		<div class="mb-3">
			<label asp-for="Description" class="form-label">Description:</label>
			<textarea asp-for="Description" class="form-control description-input" rows="4">@Model.Description</textarea>
			<span asp-validation-for="Description" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label asp-for="Price" class="form-label">Price:</label>
			<input asp-for="Price" value="@Model.Price" class="form-control price-input" autocomplete="Enter price here" aria-required="true" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>

		<div class="mb-3">
			<label asp-for="Images" class="form-label">Upload Images:</label>
			<input asp-for="Images" value="" type="file" multiple id="allImages" class="form-control file-input" hidden/>
			<input value="" type="file" multiple id="imageBatch" class="form-control"/>
			<span asp-validation-for="Images" class="text-danger"></span>
			<div class="m-1 image-preview-gallery row">

			</div>
		</div>

		

		<div class="mb-3">
			<a class="btn btn-outline-dark col-2 mb-1" data-bs-toggle="collapse" href="#colorsOptions" role="button" aria-expanded="true" aria-controls="colorsOptions">Colors</a>
			<div class="collapse m-1" id="colorsOptions">

				@foreach (var color in Model.ColorOptions)
				{
					<div class="form-check color-select">
						<input name="ColorIds" class="form-check-input" type="checkbox" multiple value="@color.Id" id="Color @color.Id" @(Model.DefaultColorIds.Contains(color.Id) ? "checked" : "")>
						<span style="background-color:@color.ColorValue;width:18px;height:18px;display:flex;border-radius:40px;border:1px solid black;"></span>
					</div>
				}
			</div>
		</div>
		<div class="mb-3">
			<a class="btn btn-outline-dark col-2" data-bs-toggle="collapse" href="#materialsOptions" role="button" aria-expanded="true" aria-controls="materialsOptions">Materials</a>
			<div class="collapse m-1" id="materialsOptions">

				@foreach (var material in Model.MaterialOptions)
				{
					<div class="form-check material-select">
						<input name="MaterialIds" class="form-check-input" type="checkbox" multiple value="@material.Id" id="Material @material.Id" @(Model.DefaultMaterialIds.Contains(material.Id) ? "checked" : "")>
						<label for="Material @material.Id">@material.Name</label>
					</div>
				}
			</div>
		</div>
		<div class="mb-3">
			<a class="btn btn-outline-dark col-2" data-bs-toggle="collapse" href="#tagsOptions" role="button" aria-expanded="true" aria-controls="tagIds">Tags</a>
			<div class="collapse m-1" id="tagsOptions">

				@foreach (var tag in Model.TagOptions)
				{
					<div class="form-check tag-select">
						<input name="TagIds" class="form-check-input" type="checkbox" multiple value="@tag.Id" id="Tag @tag.Id" @(Model.DefaultTagIds.Contains(tag.Id) ? "checked" : "")>
						<label for="Tag @tag.Id">@tag.Name</label>
					</div>
				}

			</div>
		</div>



		<div>

			<button type="submit" asp-area="Admin" asp-controller="Products" asp-action="Add" class="btn btn-primary">Add Product</button>
		</div>
	</form>
</div>

<!-- Add the Bootstrap JS script -->
@section Scripts {
	<partial name="_ValidationScriptsPartial" />
	<script src="~/js/fetchSubcategories.js"></script>
	<script src="~/js/fetchProductSeries.js"></script>
	<script src="~/js/fetchDefaultValues.js"></script>
	<script src="~/js/uploadMultipleImages.js"></script>
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Views/Products/All.cshtml
@model ProductTreeViewModel
@{
	ViewData["Title"] = "Browse All Products";
}
@inject IImageService imageService
@{
	int expandedCategory = Model.CategoryId.HasValue ? Model.CategoryId.Value : 0;
	int expandedSubcategory = Model.SubcategoryId.HasValue ? Model.SubcategoryId.Value : 0;
	int expandedProductSeries = Model.ProductSeriesId.HasValue ? Model.ProductSeriesId.Value : 0;


}
<div class="container-fluid">
	<h2 class="mb-3">@ViewData["Title"]</h2>
<div class="container">
	<a asp-controller="Categories" asp-action="Add" class="btn btn-success col-sm w-auto m-1">Add Category</a>
	<a asp-controller="Subcategories" asp-action="Add" class="btn btn-info col-sm w-auto m-1">Add Subcategory</a>
	<a asp-controller="ProductSeries" asp-action="Add" class="btn btn-primary col-sm w-auto m-1">Add Product Series</a>
	<a asp-controller="Products" asp-action="Add" class="btn btn-secondary col-sm w-auto m-1">Add Product</a>

	<a asp-controller="Colors" asp-action="All" class="btn btn-outline-dark col-sm w-auto m-1">Manage Colors</a>
	<a asp-controller="Materials" asp-action="All" class="btn btn-outline-dark col-sm w-auto m-1">Manage Materials</a>
	<a asp-controller="Tags" asp-action="All" class="btn btn-outline-dark col-sm w-auto m-1">Manage Tags</a>
</div>

<br />
<div class="container-fluid">
		<h2>Categories:</h2>
	<ul class="list-group mb-3">
		@foreach (var category in Model.Products)
		{
			<li class="list-group-item">
				<div class="row p-2">
					<a class="btn btn-outline-success w-auto" data-bs-toggle="collapse" href="#@category.Anchor" role="button" aria-expanded="true" aria-controls="@category.Anchor">@category.Name</a>

					<a asp-controller="Categories" asp-action="Edit" asp-route-categoryId="@category.Id" class="col-1 ms-auto d-flex mt-auto mb-auto link-success text-decoration-none"><i class="fa-solid fa-pencil"></i></a>
					<a onclick="return confirm('Are you sure? This will delete all of this category's subcategories, product series and products.')" asp-controller="Categories" asp-action="Delete" asp-route-categoryId="@category.Id" class="col-1 d-flex mt-auto mb-auto me-1 link-success text-decoration-none delete-button"><i class="fa-solid fa-trash"></i></a>
				</div>
				<div class="@(expandedCategory == category.Id ? "show" : "collapse")" id="@category.Anchor">

						<h3>Subcategories:</h3>
					<ul class="list-group">
						@foreach (var subcategory in category.Subcategories)
						{
							<li class="list-group-item">
								<div class="row p-2">
									<a class="btn btn-outline-info w-auto" data-bs-toggle="collapse" href="#@subcategory.Anchor" role="button" aria-expanded="false" aria-controls="@subcategory.Anchor">@subcategory.Name</a>
									<a asp-controller="Subcategories" asp-action="Edit" asp-route-subcategoryId="@subcategory.Id" class="col-1 ms-auto d-flex mt-auto mb-auto link-info text-decoration-none"><i class="fa-solid fa-pencil"></i></a>
									<a onclick="return confirm('Are you sure? This will delete all of this subcategory's product series and products.')" asp-controller="Subcategories" asp-action="Delete" asp-route-categoryId="@category.Id" asp-route-subcategoryId="@subcategory.Id" class="col-1 d-flex mt-auto mb-auto me-1 link-info text-decoration-none delete-button"><i class="fa-solid fa-trash"></i></a>
								</div>
								<div class="@(expandedSubcategory == subcategory.Id ? "collapse.show" : "collapse")" id="@subcategory.Anchor">
									<h4>Product Series:</h4>
									<ul class="list-group">
										@foreach (var series in subcategory.ProductSeries)
										{
											<li class="list-group-item card">
												<div class="row p-2">
													<a class="btn btn-outline-primary w-auto" data-bs-toggle="collapse" href="#@series.Anchor" role="button" aria-expanded="false" aria-controls="@series.Anchor">@series.Name</a>
													<a asp-controller="ProductSeries" asp-action="Edit" asp-route-productSeriesId="@series.Id" class="col-1 ms-auto d-flex mt-auto mb-auto link-primary text-decoration-none"><i class="fa-solid fa-pencil"></i></a>
													<a onclick="return confirm('Are you sure? This will delete all of this series's products.')" asp-controller="ProductSeries" asp-action="Delete" asp-route-categoryId="@category.Id" asp-route-subcategoryId="@subcategory.Id" asp-route-productSeriesId="@series.Id" class="col-1 d-flex mt-auto mb-auto me-1 link-primary text-decoration-none delete-button"><i class="fa-solid fa-trash"></i></a>
												</div>
												<div class="@(expandedProductSeries == series.Id ? "collapse.show" : "collapse")" id="@series.Anchor">
													<h5>Products:</h5>
													<ul class="list-group">
														@foreach (var product in series.Products)
														{

															<li class="list-group-item container-fluid">

																<div class="row">
																	<p class="w-auto p-3 d-inline-flex p-2 mb-auto mt-auto"> @product.Name </p>
																	<img class="col-sm-1 d-infline-flex  ms-auto md-4" style="width:120px" src="data:img/jpg;base64,@await imageService.GetAsync(product.ImageId)">
																	<a asp-controller="Products" asp-action="Edit" asp-route-productId="@product.Id" class="col-1 ms-auto d-flex mt-auto mb-auto link-secondary text-decoration-none"><i class="fa-solid fa-pencil"></i></a>
																	<a asp-controller="Products" asp-action="Delete" asp-route-productId="@product.Id" asp-route-categoryId="@category.Id" asp-route-subcategoryId="@subcategory.Id" asp-route-productSeriesId="@series.Id" class="col-1 d-flex mt-auto mb-auto me-1 link-secondary text-decoration-none delete-button"><i class="fa-solid fa-trash"></i></a>


																</div>
															</li>



														}
														<li class="list-group-item">
															<a asp-controller="Products" asp-action="Add" asp-route-CategoryId="@category.Id" asp-route-Subcategoryid="@subcategory.Id" asp-route-ProductSeriesId="@series.Id" class="btn btn-secondary">Add new</a>
														</li>
													</ul>

												</div>
											</li>
										}
										<li class="list-group-item">

											<a asp-controller="ProductSeries" asp-action="Add" asp-route-CategoryId="@category.Id" asp-route-Subcategoryid="@subcategory.Id" class="btn btn-primary">Add new</a>
										</li>
									</ul>
								</div>

							</li>
						}
						<li class="list-group-item">

							<a asp-controller="Subcategories" asp-action="Add" asp-route-CategoryId="@category.Id" class="btn btn-info">Add new</a>

						</li>
					</ul>
				</div>
			</li>
		}

	</ul>
	</div>
	</div>

@section Scripts {
	<script src="https://kit.fontawesome.com/2d34f22aab.js" crossorigin="anonymous"></script>
	<script src="~/js/confirmDelete.js"></script>
}