VelvetLeaves/VelvetLeaves.App/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VelvetLeaves.Data;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.Product;
using VelvetLeaves.ViewModels.ProductSeries;
using static VelvetLeaves.Common.ApplicationConstants;

namespace VelvetLeaves.Web.App.Areas.Admin.Controllers
{
    [Area(AdminAreaName)]
    [Authorize(Roles = $"{AdminRoleName},{ModeratorRoleName}")]

    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductSeriesService _productSeriesService;
        private readonly IImageService _imageService;
        private readonly ILogger<ProductsController> _logger;
        public ProductsController(
            IProductService productService,
            IProductSeriesService productSeriesService,
            IImageService imageService,
            ILogger<ProductsController> logger
            )
        {
            _productService = productService;
            _productSeriesService = productSeriesService;
            _imageService = imageService;
            _logger = logger;   
        }
        /// <summary>
        /// Returns all products, grouped by product series, then by subcategory, then by category, to be browsed in a tree-like structure.
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> All(int? categoryId, int? subcategoryId, int? productSeriesId)
        {
            try
            {
                var model = await _productService.GetProductTreeAsync(categoryId, subcategoryId, productSeriesId);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(int productId)
        {
            try
            {
                var model = await _productService.GetFormForEditAsync(productId);
                return View(model);

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductEditFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ImageIds = model.StartingImageIds!.ToList();
                return View(model);
            }

            try
            {
                await _productService.UpdateAsync(model);
                return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}&productSeriesId={model.ProductSeriesId}");

            }
            catch(Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }



            //return RedirectToAction("All", "Products");


        }

        [HttpGet]
        public async Task<IActionResult> Add(int categoryId, int subcategoryId, int productSeriesId)
        {
            try
            {
                var model = await _productService.GetFormForAddAsync(categoryId, subcategoryId, productSeriesId);
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductFormViewModel model)
        {
            try
            {

                if (!ModelState.IsValid)
            {
                var newOptions = await _productService.GetFormForAddAsync(model.CategoryId, model.SubcategoryId, model.ProductSeriesId);
                model.CategoryOptions = newOptions.CategoryOptions;
                model.SubcategoryOptions = newOptions.SubcategoryOptions;
                model.ProductSeriesOptions = newOptions.ProductSeriesOptions;
                model.MaterialOptions = newOptions.MaterialOptions;
                model.TagOptions = newOptions.TagOptions;
                model.ColorOptions = newOptions.ColorOptions;

                return View(model);
            }
            
                var imageIds = await _imageService.CreateRangeAsync(model.Images);
                if (imageIds.Any(id => id == null))
                {
                    ModelState.AddModelError("Image", "Image upload unsuccessful.");
                    return View(model);
                }

                model.ImageIds = imageIds!;

                await _productService.AddAsync(model);
                return LocalRedirect($"~/Admin/Products/All?categoryId={model.CategoryId}&subcategoryId={model.SubcategoryId}&productSeriesId={model.ProductSeriesId}");

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return BadRequest();
            }

        }

        [HttpGet]
        public async Task<IActionResult> FetchDefaultValues(int productSeriesId)
        {
            try
            {
                var model = await _productSeriesService.GetDefaultValues(productSeriesId);
                return Json(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }

        [HttpGet]
        public async Task<IActionResult> Delete(int productId, int categoryId, int subcategoryId, int productSeriesId)
        {
            try
            {
                await _productService.DeleteAsync(productId);
                return LocalRedirect($"~/Admin/Products/All?categoryId={categoryId}&subcategoryId={subcategoryId}&productSeriesId={productSeriesId}");

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }
    }
}

VelvetLeaves/VelvetLeaves.App/Controllers/GalleriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VelvetLeaves.Services.Contracts;
using static VelvetLeaves.Web.Infrastructure.Extensions.ClaimsPrincipalExtensions;

namespace VelvetLeaves.Web.App.Controllers
{
    [Authorize]
    public class GalleriesController : Controller
    {
        private readonly IGalleryService galleryService;
        private readonly ILogger<GalleriesController> _logger;
        public GalleriesController(IGalleryService galleryService, ILogger<GalleriesController> logger)
        {
            this.galleryService = galleryService;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Show(int id)
        {
            try
            {
            var gallery = await galleryService.GetGalleryByIdAsync(id);
            return View(gallery);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            try
            {
                var galleries = await galleryService.AllGalleriesAsync();
                return View(galleries);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
        }

        
    }
}

VelvetLeaves/VelvetLeaves.App/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using VelvetLeaves.Data.Models;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.User;
using VelvetLeaves.Web.Infrastructure.Extensions;
using static VelvetLeaves.Common.ApplicationConstants;

namespace VelvetLeaves.App.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserStore<ApplicationUser> _userStore;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IFavoriteService _favoriteService;
        private readonly ILogger<UserController> _logger;


        public UserController(
            IUserStore<ApplicationUser> userStore,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            IFavoriteService favoriteService,
            ILogger<UserController> logger)
        {
            _userStore = userStore;
            _userManager = userManager;
            _signInManager = signInManager;
            _favoriteService = favoriteService;
            _logger = logger;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Register()
        {
            RegisterFormViewModel model = new()
            {
                ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToArray()
            };
            return View(model);
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterFormViewModel model)
        {
            
            //var externalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (ModelState.IsValid)
            {
                var user = CreateUser();

                await _userStore.SetUserNameAsync(user, model.Email, CancellationToken.None);
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    //var userId = await _userManager.GetUserIdAsync(user);
                    //if (_userManager.Options.SignIn.RequireConfirmedAccount)
                    //{
                    //    return RedirectToPage("RegisterConfirmation", new { email = model.Email, returnUrl = model.ReturnUrl });
                    //}
                    
                        await _signInManager.SignInAsync(user, isPersistent: false);
                    if (this.User.IsAdmin())
                    {
                        return Redirect("Admin/Products/All");
                    }
                    return Redirect("/Home/Index");
                    
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
            
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginFormViewModel model)
        {
            

            //ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    //_logger.LogInformation("User logged in.");

                    return Redirect("/Home/Index");
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { model.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    //_logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            //_logger.LogInformation("User logged out.");
            
                // This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
                return RedirectToAction("Index","Home");
            
        }

        private ApplicationUser CreateUser()
        {
            try
            {
                return Activator.CreateInstance<ApplicationUser>();
            }
            catch
            {
                throw new InvalidOperationException($"Can't create an instance of '{nameof(ApplicationUser)}'. " +
                    $"Ensure that '{nameof(IdentityUser)}' is not an abstract class and has a parameterless constructor, or alternatively " +
                    $"override the register page in /Areas/Identity/Pages/Account/Register.cshtml");
            }
        }

        private IUserEmailStore<ApplicationUser> GetEmailStore()
        {
            if (!_userManager.SupportsUserEmail)
            {
                throw new NotSupportedException("The default UI requires a user store with email support.");
            }
            return (IUserEmailStore<ApplicationUser>)_userStore;
        }

        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var model = await _favoriteService.GetFavoritesByUserIdAsync(userId);

                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }
            
        }

        [HttpGet]
        public async Task AddToFavorites(int productId)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _favoriteService.AddToFavorites(userId, productId);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return;
            }
            
        }

        [HttpGet]
        public async Task RemoveFromFavorites(int productId)
        {
            try
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                await _favoriteService.RemoveFromFavorites(userId, productId);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return;
            }
            
        }
    }
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Views/Shared/_Layout.cshtml
@inject IHelperService helperService
@inject IConfiguration configuration
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VelvetLeaves</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VelvetLeaves.App.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@(await helperService.RootNavigationName())</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Products" asp-action="All">Products</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Galleries" asp-action="All">Galleries</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Orders" asp-action="All" asp-route-orderStatus="0">Orders</a>
                        </li>
                        @if(User.IsAdmin()){

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Promote" asp-route-orderStatus="0">Users</a>
                        </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Preferences" asp-action="Set">Preferences</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VelvetLeaves.App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Views/Shared/_OrderList.cshtml
@model AllOrderProcessViewModel

@{
	ViewData["Title"] = @Model.Title;
}
<h2>@ViewData["Title"]</h2>


	<ul class="list-group">
		<li class="list-group-item d-lg-block d-none border-1 border-dark">
				<div class="row">
					<div class="col col-lg-2 fw-bold">
						Date:
					</div>
					<div class="col col-lg-2 fw-bold">
						Recipient:
					</div>
					<div class="col col-lg-4 fw-bold">
						Address:
					</div>
					<div class="col-6 col-lg-1 fw-bold">
						Total:
					</div>
					<div class="col-6 col-lg-1 fw-bold">
						Status:
					</div>
					<div class="col-12 col-lg-2 fw-bold">
						
					</div>
				</div>
			</li>
		
		@foreach(var order in Model.Orders){
			<li class="list-group-item border-1 border-dark">
				<div class="row">
					<div class="col-12 col-lg-2 mb-2">
						<label class="d-block d-lg-none fw-bold">
							Date
						</label>
						@order.Date.ToString("d MMMM yyyy - hh:mm")
					</div>
					<div class="col-12 col-lg-2 mb-2">
						<label class="d-block d-lg-none fw-bold">
							Recipient
						</label>
						@order.FirstName @order.LastName
					</div>
					<div class="col-12 col-lg-4 mb-2">
						<label class="d-block d-lg-none fw-bold">
							Address
						</label>
						@order.StreetAddress @order.City @order.Country @order.ZipCode
					</div>
					<div class="col-6 col-lg-1 mb-2">
						<label class="d-block d-lg-none fw-bold">
							Total
						</label>
						@order.Total.ToString("f2")
					</div>
					<div class="col-6 col-lg-1 mb-2">
						<label class="d-block d-lg-none fw-bold">
							Status
						</label>
						@order.Status
					</div>
					<div class="col-12 col-lg-2 mb-2 text-center">
						<a class="btn btn-primary me-auto " asp-area="Admin" asp-controller="Orders" asp-action="Details" asp-route-orderId="@order.Id">Details</a>
					</div>
				</div>
			</li>
		}
	</ul>