VelvetLeaves/VelvetLeaves.App/Areas/Admin/Controllers/PreferencesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VelvetLeaves.Services.Contracts;
using VelvetLeaves.ViewModels.AppPreferences;
using static VelvetLeaves.Common.ApplicationConstants;


namespace VelvetLeaves.App.Areas.Admin.Controllers
{
    [Area(AdminAreaName)]
    [Authorize(Roles = AdminAndModeratorRoleNames)]
    public class PreferencesController : Controller
    {
        private readonly IHelperService _helperService;
        private readonly IImageService _imageService;
        private readonly ILogger<PreferencesController> _logger;
        public PreferencesController(IHelperService helperService, IImageService imageService, ILogger<PreferencesController> logger)
        {
            _helperService = helperService;
            _imageService = imageService;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Set()
        {
            try
            {
                var model = await _helperService.GetCurrentPreferences();
                return View(model);
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Set(AppPreferencesFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                if (model.Image != null)
                {
                    var backgroundImageId = await _imageService.CreateAsync(model.Image);
                    if (backgroundImageId == null)
                    {
                        ModelState.AddModelError("image", "Image upload unsuccessful.");
                        return View(model);
                    }
                    model.ImageId = backgroundImageId!;
                }


                await _helperService.SetCurrentPreferences(model);
                return RedirectToAction("All", "Products", new { Area = "Admin" });

            }
            catch (Exception e)
            {
                _logger.LogError(e, "Exception thrown at {Time}", DateTime.UtcNow);
                return NotFound();
            }


        }
    }
}

VelvetLeaves/VelvetLeaves.App/Areas/Admin/Views/Preferences/Set.cshtml
@model AppPreferencesFormViewModel
@inject IImageService imageService

@{
	ViewData["Title"] = "Set Application Preferences";
}


<h2>@ViewData["Title"]</h2>
<div class="container-fluid">
	<form class="form-control" method="post" enctype="multipart/form-data">
		<div class="mb-3">
			<label asp-for="RootNavigationName">Website Name</label>
			<input class="form-control" type="text" asp-for="RootNavigationName"/>
			<span asp-validation-for="RootNavigationName"></span>
		</div>

		<div class="mb-3">
			<label asp-for="RootNavigationName">Website Description</label>
			<input class="form-control" type="text" asp-for="Description"/>
			<span asp-validation-for="Description"></span>
		</div>

		<div class="mb-3">
			<label asp-for="Currency">Currency</label>
			<input class="form-control" type="text" asp-for="Currency"/>
			<span asp-validation-for="Currency"></span>
		</div>

		<div class="row">

		<div class="mb-3 col-5">
			<label asp-for="FavoriteColor">Color of "Favorite" button</label>
			<select id="favorite-color-select" class="form-select" asp-for="FavoriteColor">
				<option value="gold">Gold</option>
				<option value="pink">Pink</option>
			</select>
			<span asp-validation-for="FavoriteColor"></span>
		</div>

		<div class="mb-3 col-5">
			<label asp-for="FavoriteIcon">Shape of "Favorite" button</label>
			<select id="favorite-icon-select" class="form-select" asp-for="FavoriteIcon">
				<option value="star">Star</option>
				<option value="heart">Heart</option>
			</select>
			<span asp-validation-for="FavoriteIcon"></span>
		</div>
		<div class="col-1" id="preview-icons">
		<a><i style="color:@Model.FavoriteColor" class="fa-@Model.FavoriteIcon fa-2x fa-solid"></i></a>
		<a><i style="color:@Model.FavoriteColor" class="fa-@Model.FavoriteIcon fa-2x fa-regular"></i></a>
		

		</div>

		</div>

		<div class="mb-3">
			<label asp-for="Image" class="form-label">Background Image</label>
			<input class="form-control" asp-for="Image" class="form-control" type="file" id="formFile">
			<span asp-validation-for="Image" class="text-danger"></span>
			<div class="m-1 image-preview-gallery row">
				<img src="data:img/jpg;base64,@await imageService.GetAsync(Model.ImageId)" class="img-fluid col-2 "/>
			</div>
		</div>
		<input hidden asp-for="ImageId" value="@Model.ImageId"/>
		<button cclass="btn btn-primary" asp-area="Admin" asp-controller="Preferences" asp-action="Set" type="submit">Save</button>
	</form>
</div>

			@section Scripts{
				<script src="https://kit.fontawesome.com/2d34f22aab.js" crossorigin="anonymous"></script>
				<script src="~/js/changeFavoriteIcon.js"></script>
				<script src="~/js/uploadImage.js"></script>
				<partial name="_ValidationScriptsPartial" />
			}

				